name: CI - Build and Push Docker Image to GHCR

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write  # GHCR 푸시용 권한

env:
  GITHUB_ACTOR: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
          IMAGE_ID=$(echo "$IMAGE_ID" | tr '[:upper:]' '[:lower:]')
          docker build \
            --build-arg GITHUB_ACTOR=$GITHUB_ACTOR \
            --build-arg GITHUB_TOKEN=$GITHUB_TOKEN \
            -t $IMAGE_ID \
            -f Dockerfile .

      - name: Push Docker image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
          IMAGE_ID=$(echo "$IMAGE_ID" | tr '[:upper:]' '[:lower:]')
          docker push $IMAGE_ID