name: CI - Build and Push Docker Image to GHCR

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write  # GHCR 푸시용 권한

env:
  GITHUB_ACTOR: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    uses: github.com/nhnacademy-aiot2-lucky7/common-infra/blob/main/.github/workflows/resuable-docker-publish.yml@main
    with:
      image-name: auth-service
      use-github-token: true  # 필요하면 true, 아니면 생략 or false
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}